# - name: Collect API access token from Citrix Cloud
#   win_uri:
#     url: "https://api-eu.cloud.com/cctrustoauth2/{{ citrix_org_id }}/tokens/clients"
#     method: POST
#     content_type: application/x-www-form-urlencoded
#     body: "grant_type=client_credentials&client_id={{ citrix_client_id }}&client_secret={{ citrix_client_secret }}"
#     return_content: yes
#   register: citrix_token

- name: Convert hosting json to ansible fact
  set_fact: 
    hosting_name:
      ConnectionDetails:
        Name: "test"
    hosting_connection_type:
      ConnectionDetails:
        ConnectionType: AzureRM
    hosting_application_id:
      ConnectionDetails:
        ApplicationId: "test"
    hosting_application_secret:
      ConnectionDetails:
        ApplicationSecret: "test"
    hosting_subscription_id:
      ConnectionDetails:
        SubscriptionId: "test"
    hosting_active_directory_id:
      ConnectionDetails:
        ActiveDirectoryId: "test"
    hosting_environment:
      ConnectionDetails:
        Environment: AzureCloud

- name: combining the facts
  set_fact:
    hosting_object: "{{ hosting_name | combine(hosting_connection_type, recursive=True) | combine(hosting_application_id, recursive=True) | combine(hosting_application_secret, recursive=True) | combine(hosting_subscription_id, recursive=True) | combine(hosting_active_directory_id, recursive=True) | combine(hosting_environment, recursive=True) }}"

- name: debug output 2
  ansible.builtin.debug:
    msg: "{{ hosting_object }}"

# - name: Get Citrix resource locations
#   win_uri:
#     url: https://registry.citrixworkspacesapi.net/{{ citrix_org_id }}/resourcelocations
#     method: GET
#     content_type: application/json
#     headers: "{'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
#     return_content: yes
#   register: citrix_resource

