- name: Built the environment dictonary
  set_fact:
    branches:
        default: "pois" 
        cards:   "card"
        flowers: "flow"

- name: Set the environment short
  set_fact:
    environment_short: "{{branches[branch | lower]}}"

- name: Collect API access token from Citrix Cloud
  win_uri:
    url: "https://api.cloud.com/cctrustoauth2/{{ citrix_org_id }}/tokens/clients"
    method: POST
    content_type: application/x-www-form-urlencoded
    body: "grant_type=client_credentials&client_id={{ citrix_client_id }}&client_secret={{ citrix_client_secret }}"
    return_content: yes
  register: citrix_token

- name: Get Citrix Cloud sites
  win_uri:
    url: https://api.cloud.com/cvad/manage/Sites/{{ citrix_org_id }}
    method: GET
    content_type: application/json
    headers: "{'Citrix-CustomerId': '{{ citrix_org_id }}', 'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
    return_content: yes
  register: citrix_sites

- name: Debug sites
  ansible.builtin.debug:
    msg: "{{ citrix_sites.json }}"

- name: Set Citrix Cloud site ID
  set_fact:
    citrix_site_id: "{{ citrix_sites.json.Id }}"

- name: Debug sites
  ansible.builtin.debug:
    msg: "{{ citrix_site_id }}"

- name: Get Citrix Cloud hypervisor connection
  win_uri:
    url: https://api.cloud.com/cvad/manage/hypervisors
    method: GET
    content_type: application/json
    headers: "{'Citrix-CustomerId': '{{ citrix_org_id }}', 'Citrix-InstanceId': '{{ citrix_site_id }}', 'User-Agent': 'GET', 'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
    return_content: yes
  register: citrix_hypervisor

- name: Set Citrix Cloud hypervisor ID
  set_fact:
    citrix_hypervisor_id: "{{ data | json_query(querystr) }}"
  vars:
    data: "{{ citrix_hypervisor.json }}"
    querystr: "Items[?contains(Name,'{{ prefix }}-{{ branch }}-AzureConnection')].Id | [0]" #First result

- name: Debug hypervisor
  ansible.builtin.debug:
    msg: "{{ citrix_hypervisor_id }}"

- name: Get Citrix Cloud zones
  win_uri:
    url: "https://api.cloud.com/cvad/manage/zones"
    method: GET
    content_type: application/json
    headers: "{'Citrix-CustomerId': '{{ citrix_org_id }}', 'Citrix-InstanceId': '{{ citrix_site_id }}', 'User-Agent': 'GET', 'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
    return_content: yes
  register: citrix_zones
  when: citrix_hypervisor_id != None

- name: Set Citrix Cloud zone ID
  set_fact:
    citrix_zone_id: "{{ data | json_query(querystr) }}"
  vars:
    data: "{{ citrix_zones.json }}"
    querystr: Items[?Name == '{{ prefix }}-{{ branch }}'].Id | [0]
  when: citrix_hypervisor_id != None

- name: Debug zone
  ansible.builtin.debug:
    msg: "{{ citrix_zone_id }}"
  when: citrix_hypervisor_id != None

- name: Creating Citrix Cloud hosting body 
  set_fact: 
    hosting_name:
      ConnectionDetails:
        Name: "{{ prefix | lower }}-{{ environment_short }}-{{ deploymentname }}-azure"
    hosting_connection_type:
      ConnectionDetails:
        ConnectionType: AzureRM
    hosting_application_id:
      ConnectionDetails:
        ApplicationId: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    hosting_application_secret:
      ConnectionDetails:
        ApplicationSecret: "{{ lookup('env', 'AZURE_SECRET') }}"
    hosting_subscription_id:
      ConnectionDetails:
        SubscriptionId: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    hosting_active_directory_id:
      ConnectionDetails:
        ActiveDirectoryId: "{{ lookup('env', 'AZURE_TENANT') }}"
    hosting_environment:
      ConnectionDetails:
        Environment: AzureCloud
    hosting_zone:
      ConnectionDetails:
        Zone: "{{ citrix_zone_id }}"
  when: citrix_hypervisor_id != None

- name: combining the facts for the hosting body
  set_fact:
    hosting_object: "{{ hosting_name | combine(hosting_connection_type, recursive=True) | combine(hosting_application_id, recursive=True) | combine(hosting_application_secret, recursive=True) | combine(hosting_subscription_id, recursive=True) | combine(hosting_active_directory_id, recursive=True) | combine(hosting_environment, recursive=True) | combine(hosting_zone, recursive=True) }}"
  when: citrix_hypervisor_id != None

- name: debug output 2
  ansible.builtin.debug:
    msg: "{{ hosting_object }}"
  when: citrix_hypervisor_id != None

- name: Post Citrix Cloud hypervisor connection
  win_uri:
    url: https://api.cloud.com/cvad/manage/hypervisors
    method: POST
    content_type: application/json
    headers: "{'Citrix-CustomerId': '{{ citrix_org_id }}', 'Citrix-InstanceId': '{{ citrix_site_id }}', 'User-Agent': 'POST', 'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
    body: "{{ hosting_object | to_json }}"
    status_code: [200, 201]
    return_content: yes
  register: citrix_new_hypervisor
  when: citrix_hypervisor_id != None

- name: debug output 2
  ansible.builtin.debug:
    msg: "{{ citrix_new_hypervisor }}"
  when: citrix_hypervisor_id != None

- name: Set the new hypervisor id
  set_fact:
    citrix_new_hypervisor_id: "{{ citrix_new_hypervisor.json.Id }}"
    msg: "{{ citrix_new_hypervisor }}"
  when: citrix_hypervisor_id != None

- name: Creating Citrix Cloud resource body 
  set_fact: 
    resource_name:
      Name: "{{ environment_short }}-{{ deploymentname }}-default"
    resource_connection:
      ConnectionType: AzureRM
    resource_region:
      Region: "{{ azure_region }}.region"
    resource_virtual_network:
      VirtualNetwork: "{{ azure_region }}.region/virtualprivatecloud.folder/rg-golab-{{ environment_short }}-vnet.resourcegroup/vnet-infra-{{ environment_short }}.virtualprivatecloud"
    resource_subnets:
      Subnets: [ "{{ azure_region }}.region/virtualprivatecloud.folder/{{ azure_region }}.region/virtualprivatecloud.folder/rg-golab-{{ environment_short }}-vnet.resourcegroup/vnet-infra-{{ environment_short }}.virtualprivatecloud/sn-infra-{{ environment_short }}.network" ]

- name: Combining the facts for the resource body
  set_fact:
    resource_object: "{{ resource_name | combine(resource_connection, recursive=True) | combine(resource_region, recursive=True) | combine(resource_virtual_network, recursive=True) | combine(resource_subnets, recursive=True) }}"

- name: object
  ansible.builtin.debug:
    msg: "{{ resource_object }}"

- name: Post Citrix Cloud hypervisor connection
  win_uri:
    url: https://api.cloud.com/cvad/manage/hypervisors/{{ citrix_new_hypervisor_id }}/resourcePools
    method: POST
    content_type: application/json
    headers: "{'Citrix-CustomerId': '{{ citrix_org_id }}', 'Citrix-InstanceId': '{{ citrix_site_id }}', 'User-Agent': 'POST', 'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
    body: "{{ resource_object | to_json }}"
    return_content: yes
    status_code: [200, 201]
  register: citrix_new_resource

- name: debug citrix_new_resource
  ansible.builtin.debug:
    msg: "{{ citrix_new_resource }}"
