# - name: Collect API access token from Citrix Cloud
#   win_uri:
#     url: "https://api-eu.cloud.com/cctrustoauth2/{{ citrix_org_id }}/tokens/clients"
#     method: POST
#     content_type: application/x-www-form-urlencoded
#     body: "grant_type=client_credentials&client_id={{ citrix_client_id }}&client_secret={{ citrix_client_secret }}"
#     return_content: yes
#   register: citrix_token

# - name: Get Citrix resource locations
#   win_uri:
#     url: https://registry.citrixworkspacesapi.net/{{ citrix_org_id }}/resourcelocations
#     method: GET
#     content_type: application/json
#     headers: "{'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
#     return_content: yes
#   register: citrix_resource

- name: Configure the hosting connection
  include: hosting.yml